### ISSUE TITLE
Archive Broken?

### ISSUE THREAD

**Issue by mojo706** [andreberg/Meslo-Font#16]
Hello, I have tried 3 times on three different occasions to download the zip archive I even cloned the repo but to no success. Is th archive broken. Please confirm.

**Comment by andreberg** [comment]
Not to my knowledge, no. Let me try downloading it to confirm... 

Just so I understand, because there is more than one way to download: 

which ZIP did you download? The zip from the complete repository (e.g. https://github.com/andreberg/Meslo-Font/archive/master.zip) or did you by chance view a version zip as a raw file to download the latest version only (e.g. click View Raw on this page: https://github.com/andreberg/Meslo-Font/blob/master/dist/v1.2.1/Meslo%20LG%20DZ%20v1.2.1.zip)

**Comment by mojo706** [comment]
the first one

**Comment by andreberg** [comment]
Weird. I have no problems opening the ZIP after I downloaded it with Firefox 23 on OS X. 
Can you try the second option of my last post?

Let me know if it doesn't work, I can try uploading the ZIP to a cloud sharing service...

**Comment by mojo706** [comment]
Hello and thanks for responding. It works now both the first and second option. Must be that I'm on Firefox 25 on Ubuntu, may be something else thanks again. I like the fonts.
