### ISSUE TITLE
Meslo not identified as fixed-width font?

### ISSUE THREAD

**Issue by pnoeric** [andreberg/Meslo-Font#2]
I'm trying to use Meslo in a terminal app that requires a fixed-width font, but when I choose Meslo, it's claiming the font isn't fixed-width. I thought that was odd so I launched Font Book on the Mac and sure enough, when I choose to see "fixed width fonts" it doesn't appear in the list, but Meslo is there when I choose "all fonts."

I'm a Mac power user but not a developer, so I'm not sure what's going on, but I'm GUESSING there's a flag in the font that says "I'm a fixed-width font" and it's just not properly set in the font.

Let me know if there's any other info I can provide. Love the font and the thinking that went into it, and would love to use it in my terminal app.

best
Eric

**Comment by andreberg** [comment]
That behaviour is normal. The Fixed Width Fonts group is a pre-existing group (as opposed to a smart group) but once you install new fonts you often need to manually drop them in there if they are fixed-width. At least that's the case on my Macs. I also have to drag Meslo into this group each time I do a new test build. About the flags: yes these exist - there's a whole amada of those font identification systems as they are called. PANOSE for example is one and each OS basically has its own parameters. But these flags already were set correctly in Apple's Menlo - which is what Meslo is based on. The only thing that I changed is that I set the MODERN flag for the Windows console to recognise it as a Font usable with Window's version of the Terminal.

**Comment by andreberg** [comment]
Oh and to my knowledge what group in Font Book a font is assigned to doesn't affect if the font is usable with the Terminal. You should be able to use Meslo with the Terminal regardless. Especially Apple's Terminal is really forgiving as to what font you use: Fixed-width or otherwise. I just made a really whacky Terminal style using Grass with the Curlz font (ugh). On the Windows side this is not the case: you sorta have to hack this together by touching would-be-dangerous parts of the OS to make it work - in addition to having a font configured in a proper way.

**Comment by andreberg** [comment]
What can be a factor though that you may not see the Terminal window updating and showing Meslo correctly is if do not have Anti-alias enabled in your current Terminal style. With some fonts that do not support bitmap hints (Meslo being one of them) you really need Anti-alias to be enabled otherwise the Terminal will sometimes just not use the new font (or the result really looks odd).

**Comment by pnoeric** [comment]
Hi Andre, thanks-- didn't know about the fact that Apple's "fixed with fonts" group was something special.

I'm actually using a different (much more powerful) terminal/SSH app called SecureCRT, and it's still claiming that the font isn't fixed with. There's definitely an issue here someplace, but I don't know if it's with SecureCRT or they are looking for something special in the font that isn't there. I've asked their tech folks to look at this thread... hopefully they will so this can be resolved. :-)

**Comment by andreberg** [comment]
Ah I see. You said "in a terminal app". I didn't catch that. 
Does Apple's Menlo work with SecureCRT?

**Comment by pnoeric** [comment]
It does-- just confirmed it with both "Menlo Regular" and "Menlo Bold." No problem, the app didn't complain.

**Comment by pnoeric** [comment]
Incidentally, not sure if it would help you at all, but here's the SecureCRT site (you can get a free trial version): http://www.vandyke.com/products/securecrt/mac_osx.html

And like I mentioned, I've been talking to their tech support folks and asked them to look at this thread, so maybe someone from over there will chime in to help solve this.

BTW when I go to change the font in SecureCRT, I can get into the font picker (under Session Options > Appearance), and I can click Meslo, but as soon as I click "OK" to close the font picker and use that font, a dialog appears that says "You haven't chosen a fixed-width font." So it's not acting weird or giving me a crummy display or whatever... it's just flat-out rejecting it immediately. That's why my first suspicion was just a simple issue of a flag/flags not being set right.

**Comment by andreberg** [comment]
Hm.... it's a long stretch but maybe it's the font format. Apple's Menlo is a TrueType collection and Meslo is a OpenType TrueType font format. I will look into it when I have some spare time. Hey if you hear back from them that SecureCRT needs a specific font format (often it's TrueType only and no PS1 fonts for example) do post back here please.

**Comment by andreberg** [comment]
Curious. I guess it depends on how they define fixed-width font because they seem to do some extra verification that go extra of just checking what flags the font designer has set for the font identification system. I'll have to fiddle around a little with SecureCRT demo and see what I can do but my general strategy so far has been to not change anything that doesn't need to be changed about Menlo - because Apple has much more resources in testing their Fonts than I could possibly have.

**Comment by pnoeric** [comment]
Yeah, I think that's the right strategy for what you're doing.

SecureCRT's tech support has been very responsive, so I'm hoping for some positive news from them soon. I'll post when I hear anything. And again, thank YOU for your attention to this issue so far...

**Comment by andreberg** [comment]
Ok, I finally got around to giving SecureCRT a try. I did not get very far unfortunately. Every time I was clicking the Font... button SecureCRT crashes with the following backtrace (shortened from about 43 lines):

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib               0x91f80ef6 __kill + 10
1   libSystem.B.dylib               0x91f80ee8 kill$UNIX2003 + 32
2   libSystem.B.dylib               0x9201362d raise + 26
3   libSystem.B.dylib               0x920296e4 abort + 93
4   libSystem.B.dylib               0x91fa5c9b _Unwind_Resume + 59
5   com.vandyke.SecureCRT           0x004b4a36 QHash<QSound*, NSSound const*>::remove(QSound\* const&) + 28758
6   com.apple.HIToolbox             0x98b6ef2f DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec*) + 1567

This may be because of some font I have installed (I do have about 400 fonts installed right now) so I started uninstalling fonts at random but I couldn't get rid of the crash. At this point I am not sure about how to proceed since I am in the middle of jobs and I do not want to mess too much with my production system. 

I think it would be best right now to just be told what attributes they require from a font to be identified fixed width by SecureCRT instead of finding out by trial and error.
