### ISSUE TITLE
Rendering on Windows 7 not fixed-width?

### ISSUE THREAD

**Issue by oconnor0** [andreberg/Meslo-Font#6]
When I use Meslo LG M in Sublime Text 2 or Eclipse Indigo on Windows 7, there are some combinations of letters that aren't rendered as fixed-width. I asked the Sublime Text 2 developers & they are using the normal Windows font rendering API.

Here's some example text that displays this behavior. The pipes don't line up.

```
|-------------+----------------------------------------------------|
| asm.c       | some assembler functions                           |
| asm.h       | some assembler macros                              |
| ast.c       | the ast for Potion code in-memory                  |
| callcc.c    | creation and calling of continuations              |
```

**Comment by clippit** [comment]
Same issue. Here is a sublime 2 screenshot. When `font_size` is 19, it looks well.

![sublime 2 meslo](http://i.imgur.com/HGcjN.png)

**Comment by phpfaber** [comment]
I came here with the same issue. What I noticed "2" has problems on some font sizes. Maybe more symbols have such issues as well but not discovered yet.
![image](http://i.imgur.com/72q4F.png)

**Comment by tborychowski** [comment]
I'm also having similar issues. I't not only in SublimeText, I've checked e.g Ms Word and it's still the case. 
When I set the font size to e.g. 9, 12, 13 or 14px - it stops being a fixed-width font.
font size 12px:
![font12](https://f.cloud.github.com/assets/392513/10778/76938894-4532-11e2-9519-43a557895417.png)
font size 13px:
![font13](https://f.cloud.github.com/assets/392513/10779/7ef7f59c-4532-11e2-9939-d96ed066a123.png)

Also when I set the font size to 10pt - I see strange "artifacts" (rendering?) on some characters when they are bolded ('=' looks like the bottom line is twice as bold as the top one and 'g' has a big dot over the top of the letter).
What's strange is that it only happens when the background is white:
![arts](https://f.cloud.github.com/assets/392513/10775/5aabd974-4532-11e2-8120-279a1bb573d0.png)
it's fine when bg is dark:
![arts-dark](https://f.cloud.github.com/assets/392513/10776/5e904d36-4532-11e2-8c76-6de03287f6a2.png)

**Comment by jims** [comment]
Same issue here, and just as golovan pointed out, it seems it's the number 2 that has a smaller width than at least the rest of all numbers and letters.
![align](https://f.cloud.github.com/assets/74543/10709/4908e106-452f-11e2-8224-5f0fbaaf277d.png)

**Comment by andreberg** [comment]
I just released v1.2 that will hopefully fix these problems.

**Comment by phpfaber** [comment]
Wow! Good gift for NY! Will be testing now. Thanks :)

**Comment by phpfaber** [comment]
andreberg, yes, this version is working great! But you know.. what I noticed right now, with this option

```
"font_options":
[
    "directwrite"
], 
```

1.0 version is working as well... Just noticed that. 

Thanks a million one more time!

**Comment by andreberg** [comment]
Thanks for testing. 

That's pretty interesting. I don't recognize this option... it doesn't look like a Registry setting. 
Is it from Sublime, or somwhere else, if I may ask?

**Comment by phpfaber** [comment]
andreberg, 

yep... I found and used this sublime's option recently. Some info is here http://deldy.dk/post/sublime-text-directwrite or you may google it.

**Comment by andreberg** [comment]
Ah, right... now I remember. I think I read something about DirectWrite on the ClearType technology site some time ago. Off to check out Sublime now tho :)

**Comment by tborychowski** [comment]
Thanks @andreberg very much! Font looks great! And thanks @golovan for the sublime option - it improves the rendering!
